Percentual sipm threshold
next-exp/IC pull request #354
Opened 2017-10-04 12:16 UTC by gonzaponte

This PR introduces the possibility of using two types of thresholds for the SiPMs:
- Common: a single value in pes for all the SiPMs.
- Individual: each SiPM has its own threshold based on a common percentage of noise reduction. Since each SiPM has a different PDF, they also have different thresholds.

The code to compute the thresholds based on the percentage was already in IC, but it has been cleaned up a bit. The cython function to extract the signal from the sipms has been adapted to take both types of thresholds and a flag has been introduced in the cities to switch between both modes. The tests included in this PR are, perhaps, still not very exhaustive. I have introduced three:
- A test for `irene` to check that can run in both modes (this is actually a parametrization of a previous test to run with the two values of the flag). However, it does not check the output, as this is more complicated, but it is somehow complemented with:
- Two tests for the function `signal_sipm` in `peak_functions`, one for each threshold mode. These tests ensure the output of the function is the one we expect.

The configuration files from now on must include a new option `thr_sipm_type` that must be equal to `"common"` or to `"individual"` (case insensitive).

2017-10-04 12:23 UTC, gonzaponte commented
I have had doubts with regard to the removal of the type of the argument `thr` in `signal_sipm`. Initially, I thought it would be simpler to remove it rather than changing it to an array so the tests would remain unchanged and therefore everything is more robust. I didn't realize at the time that there were no tests for that function. Now it is not clear to me whether it is better to accept an untyped value (which is later converted into an array anyway) or to force the user the call it with an array. The latter makes the function simpler, maybe, but the former is more comfortable. There is probably not a big difference, but it is open for discussion.

2017-10-06 12:00 UTC, jahernando reviewed
I do not understand why you replace the typed parameter 'trh' in invisible_cities/reco/peak_functions_c.pyx.

This is not related with the PR but in the line 450, I assume threshold is in pes, but to apply a filter is multiplied by adc_to_pes, it should not be divided?

2017-10-06 12:07 UTC, gonzaponte commented
> I do not understand why you replace the typed parameter 'trh' in invisible_cities/reco/peak_functions_c.pyx.

So it can accept both a `float` (common threshold) and an `array` (individual thresholds).

> In the line 450, I assume threshold is in pes, but to apply a filter is multiplied by adc_to_pes, it should not be divided?

I assume is line 450 of `peak_functions_c.pyx`. This is actually a wrong name that has been there since the beginning. It is actually `pes_to_adc`.
Actually, this is everywhere, even in our database... Since this has nothing to do with this PR, I will open an issue.

2017-10-06 12:07 UTC, jahernando requested changes
Please add a comment in base_cities to indicate the possible values of the thr_sipm_type and thr_sipm

2017-10-06 12:09 UTC, jahernando commented
> This is actually a wrong name that has been there since the beginning.
> 
> 

I see this is the usual JJ’s tactic of confusing the enemies and the friends around. 

José Ángel

skype: joseahernando
phone: +34 698 186 151
@jagelhm

2017-10-06 12:11 UTC, gonzaponte commented
> Please add a comment in base_cities to indicate the possible values of the thr_sipm_type and thr_sipm

I think it is obvious. There are two comments indicating what `thr_sipm` means in each case.

```
 if   conf.thr_sipm_type.lower() == "common":
    # In this case, the threshold is a value of threshold in pes
    [...]
elif conf.thr_sipm_type.lower() == "individual":
    # In this case, the threshold is a percentual value
    [...]
else:
    raise ValueError(("Wrong value in thr_sipm_type. It must"
                      "be either 'Common' or 'Individual'"))
```

2017-10-06 12:13 UTC, jahernando commented
Yes, when you read the code, but not in the header comments of the class, the first place one look to understand the behavior,

> El 6 oct 2017, a las 14:11, Gonzalo <notifications@github.com> escribió:
> 
> Please add a comment in base_cities to indicate the possible values of the thr_sipm_type and thr_sipm
> 
> I think it is obvious. There are two comments indicating what thr_sipm means in each case.
> 
>  if   conf.thr_sipm_type.lower() == "common":
>     # In this case, the threshold is a value of threshold in pes
>     [...]
> elif conf.thr_sipm_type.lower() == "individual":
>     # In this case, the threshold is a percentual value
>     [...]
> else:
>     raise ValueError(("Wrong value in thr_sipm_type. It must"
>                       "be either 'Common' or 'Individual'"))
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/nextic/IC/pull/354#issuecomment-334737323>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AHysBVgkkw-f5-cUFyTSqP4wlNgnJSIkks5sphj8gaJpZM4PthI_>.
> 

José Ángel

skype: joseahernando
phone: +34 698 186 151
@jagelhm

2017-10-06 12:14 UTC, gonzaponte commented
Ok. I agree.

2017-10-06 14:27 UTC, jahernando submitted a review, later dismissed
The PR includes the possibility of do Zero-Supression of SiPM wave-forms, using a threshold on the cdfs of the SiPMs noise, and accepting only time slices in the wf with a signal with a p-probability greater than a certain value. 

The PR extends the interface of signal_sipm function, that now it includes a parameter to select the ZS method (thr_sipm_type) and a parameter of the actual threshold (thr_sipm) value(s).

There are two test to verify that the signal_sipm is properly doing the ZS for the two method 'common' and 'individual'.

Not related with this PR, it seems to me that an extra test is needed to verify the operation of ComputeThreshold class. Simply to check that the returned thresholds for the individual SiPMs correspond in fact to a given value of their cdfs.

I approve the PR.

2017-10-06 14:32 UTC, jahernando reviewed
In fact, I think is better that you include the test of the ComputeThreshold class that I was commenting before, in this PR, to have a more consistent picture.

2017-10-09 15:26 UTC, gonzaponte commented
I don't know why the test `test_uniform_smearing_stats` fails in travis. I can't even get a failure in my computer. My version of hypothesis is quite old (3.12.0), but this is something purely statistical. It should only fail 0.3% of the time, and I allow 1 failure in 5 runs.

2017-10-09 15:31 UTC, jacg commented
Two things:

1. `pip install hypothesis 3.28`
2. `HYPOTHESIS_PROFILE=hard pytest -k uniform_smearing_stats`

2017-10-09 15:50 UTC, gonzaponte commented
Oh, I thought we had switched back to `dev`. The `hard` profile is causing of the failure. Are we changing the profile to `dev` back again? Should I be more permissive in the assertion or use the context manager to reduce the number of examples for that particular test?

2017-10-09 15:58 UTC, jacg commented
> I thought we had switched back to `dev`

Oh nonononnonoooooo! Why would we?

The whole point of `dev` is that we use it during development, so that we get quick turnaround in our local repos as we're hacking away. The whole point of `hard` is that Travis can run it, because given that Travis already has to download and install our whole system, the relative overhead of running more thorough tests isn't that significant and, usually, there is no human sitting there doing nothing but waiting for it to complete.

> Are we changing the profile to `dev` back again?

For Travis? No way! (Travis *never* had `dev`, `dev` is an emasculated version of the default profile.)

`dev` skimps on the testing. We're prepared to live with it in our local repos, as long as someone, somewhere, runs the hard tests regularly for us. That someone is Travis.

> Should I be more permissive in the assertion or use the context manager to reduce the number of examples for that particular test?

Sorry, can't help you there, as that would require me to dig into details for which I have no time at the moment.

2017-10-09 16:08 UTC, gonzaponte commented
Ok, I agree. Thank you.

2017-10-11 20:07 UTC, jjgomezcadenas commented
@jahernando this is stale. I think this is an important PR to include in our next release.

2017-10-20 02:17 UTC, abotas commented
The PR looks great and very thoroughly tested to this reviewer! 

I think it's unfortunate that we add a flag "common" or "individual for sipm thr type. But if we want to keep the common threshold in some cases, which i think we do, the flag seems necessary. 

Just to reiterate, this PR allows individual `thr_sipm`, (the time bin by time bin cut)  but not individual `thr_sipm_s2` (the integral s2 cut), correct? 

---
One thing that bothers me a little, is that if we decide to use individual `thr_sipm`s, it seems like using a common `thr_sipm_s2` on the integral gets a little messy. I am imagining that we might introduce a bias where our software will incorrectly show noisy SiPMs seeing considerably less light than well behaved SiPMs. _Particularly for long s2s, SiPMs that are slightly more noisy might have to record considerably more light to pass the `thr_sipm_s2`._ Does this make sense? It's not a problem with the PR, but I think it is something we need to think about this a little carefully.

2017-10-20 02:41 UTC, abotas commented
There are quite a few commits here so I will refrain from merging until tomorrow, just to give other reviewers one last (quick) chance to complain if they want! But again, the PR looks good and ready to this reviewer!

2017-10-21 02:24 UTC, abotas approved these changes
Approved.

2017-10-21 03:20 UTC, abotas commented
Rebased.

2017-10-21 03:23 UTC, merged