Add chi2 and errors bug fixing
next-exp/IC pull request #359
Opened 2017-10-06 01:20 UTC by bpalmeiro

- Chi2
Implemented chi2 computation, based on scipy.stat.chisquare is only valid when data smearing is Poisson distributed. So, a general chi2 function is added, with formula extracted from [1].

- Errors
Fit errors, given by scipy.optimize.curve_fit were not correct as flag absolute_sigma was set to false. When true, "[data] sigma describes one standard deviation errors of the input data points", so covariance matrix estimation is based on these values. Otherwise, data sigma is only taken as "relative weights of the data points" and covariance matrix is not affected by the overall magnitude of the values in sigma, just by relative magnitudes.

Both improvements are shown in https://github.com/bpalmeiro/ICARO/tree/Chi2_demostration

[1]  Numerical Recipes. The Art of Scientific Computing, 3rd Edition, 2007, ISBN 0-521-88068-8. Pages 778-780

2017-10-06 08:06 UTC, gonzaponte requested changes
Great work! Very well documented and demonstrated.

2017-10-06 08:06 UTC, gonzaponte commented on invisible_cities/core/fit_functions.py
> +
ndf is not documented

2017-10-06 08:06 UTC, gonzaponte commented on invisible_cities/core/fit_functions.py
> +
use a variable to hold the result of `fitx != 0`. It is used in 4 different places.

2017-10-06 08:06 UTC, gonzaponte commented on invisible_cities/core/fit_functions.py
> +        sigma_r   = None
You can use `sigma_r = kwargs.get("sigma")` which returns `None` if the key is not found.

2017-10-06 08:28 UTC, jjgomezcadenas commented
Really good work. The Galician gang (GG's) are increasing even more their level of Karma.
I suggest to turn the examples in the notebooks into tests! Simply take the results that you obtain for chi2 and P-value with both methods and assert them. Like that the test (with a few comments) also documents the work!

Incidentally, the result:
chi2     : 0.9911404817192085
P-value  : 1.328398e-21

Which you obtain for Poissonian errors with old method does not make sense for P-value. 

Good job (I will live @gonzaponte to approve it, after you add the little changes he suggests and perhaps the docs-test. :)!

2017-10-07 08:33 UTC, gonzaponte commented on invisible_cities/core/fit_functions.py
> +
I don't want to be pedantic, but can we replace `len(data)` by `number of data points`?

2017-10-08 17:02 UTC, gonzaponte submitted a review, later dismissed

2017-10-08 17:11 UTC, gonzaponte commented
I like this, but a second view made me realize that the `ndf` argument in `get_chi2_and_pvalue` is optional and set to 1. This shouldn't be like that, as the number of degrees of freedom is essential to the output. Also, at the risk to be pedantic again, can you mark the optional arguments in the docstring? Finally, we must add tests to ensure this new function is working properly and review those of the `fit` function which are probably very soft on the `chi2` output.

2017-10-11 20:05 UTC, jjgomezcadenas commented
This review is stale, @gonzaponte, why? No advantage in letting open PRs which appear good enough to grow old. We are not running a winery here.

2017-10-12 09:48 UTC, gonzaponte commented
> why?

Because we are still working on making it right once and for all. There are different interpretations of the parameters for scipy's `curve_fit` function. We want to handle all of them correctly. It seems stale, but we are pera-discussing it behind the scenes.

We have a working version which yields incorrect results only for the chi2 value and the errors of the parameters (which we are not paying too much attention to). We need to fix this, but it will not have a big impact on our lives.

2017-10-20 21:50 UTC, gonzaponte reviewed
Good work! This looks nice!

2017-10-20 21:50 UTC, gonzaponte commented on invisible_cities/reco/corrections_test.py
> +from ..icaro.hst_functions import poisson_sigma
Please move `poisson_sigma` to `core_functions.py`. The `icaro` package will (probably) be removed in the near future.

2017-10-20 21:50 UTC, gonzaponte commented on invisible_cities/core/fit_functions.py
> +    if np.size(sigma_r) is not 1:
Mmm, I don't like this `size` check... How about setting the default to `np.ones` of the corresponding size and applying the `nonzero` selection over it?

2017-10-20 21:50 UTC, gonzaponte commented on invisible_cities/reco/corrections_test.py
> +    x     = x[:-1] + np.diff(x) * 0.5
This is the same as the function `shift_to_bin_centers` in the `icaro` package. Can we move it also to `core` and use it here?

2017-10-20 21:50 UTC, gonzaponte commented on invisible_cities/reco/corrections_test.py
>      assert f.chi2 < 3
This `f.chi2 < 3` is maybe a bit soft. I think we can `flaky` these two tests.

2017-10-21 07:17 UTC, jjgomezcadenas commented
@gonzaponte I don't think that ICARO will be removed from IC!!!!

What we are going to do is to prototype in ICARO (repo), and the promote to IC/ICARO when we are happy enough, that means that PRS to IC/ICARO will continue but with the standard level of strictness (tests and such). The package will not disappear.

This said, poisson_sigma it's probably better in core

2017-10-21 10:11 UTC, gonzaponte commented
@jjgomezcadenas Ok, then it is not obvious to me where these functions (those in `icaro/hst_functions.py` that are not for plotting) should go. I think we can postpone that discussion for another PR, do you agree?

2017-10-21 10:28 UTC, jjgomezcadenas commented
Why not stat_tools.py also in IC/ICARO? Either now or in a different PR, your pick

2017-10-21 10:41 UTC, gonzaponte commented
> Why not stat_tools.py also in IC/ICARO?

Agree. I was thinking about something like that too.

> Either now or in a different PR, your pick

I like to maintain PRs as self-contained as possible, so I would make a separate PR. But it can be performed by the same author as this one :)

2017-11-26 13:57 UTC, jjgomezcadenas commented
What on earth happened here, @gonzaponte, @bpalmeiro? This is huger amount of work, we need to get it out of the way

2017-11-26 14:00 UTC, gonzaponte commented
This is almost ready (I still need to review it a bit), however I am going to sit with @bpalmeiro to show him how to clean up the PR (it contains far too much noise). The time difference and the busy last weeks didn't help.

2017-12-04 23:57 UTC, jjgomezcadenas commented
This has been opened for ever, @bpalmeiro, @gonzaponte . Are you serious or what?

2017-12-05 10:46 UTC, gonzaponte commented
1. This is not urgent. There is nothing depending on this PR.
2. This has no conflict with TBR.
3. We will use this PR to practice some of the git-related operations and leave a clean history while reviewing with peras. However, @bpalmeiro is on vacation. I was going to do it by myself and redo it with him when he is back, but:
4. I don't have time AT ALL.
5. @bpalmeiro is back next week. We will begin the pera-review + cleanup then.
6. Again, there is nothing urgent here. Nothing in the data-processing chain depends on this. Please, keep calm, I am doing my best.

2018-01-08 17:58 UTC, gonzaponte approved these changes
This PR fixes a long-term issue with the definition of the chi2 and the p-value. The calculations have been encapsulated within a function, which is tested. The previous test suite for the rest of the code has also been fixed, improved and extended.

Great job!

2018-01-08 18:15 UTC, merged