Addition of simulation of low frequency noise
next-exp/IC pull request #500
Opened 2018-07-05 15:20 UTC by andLaing

Simulation of low frequency noise effects
seen in the PMTs to the sensor simulation.

Involves changes to the database to allow
parameters from the detector to be updated
whern needed.

load_db.py:
New funciton added 'PMTLowFrequencyNoise'
which reads the mapping of PMTs to
front end boxes and the frequencies
and magnitudes to be used in the simulation.

low_frequency_noise.py:
New function that randomises contributions
and returns a function to access these
according to front end board mapping

2018-07-05 15:21 UTC, andLaing commented
This PR is a tidied and rebased version of the code I used for this: http://next.ific.uv.es/DocDB/0007/000706/001/lowFreqNoiseSim.pdf study.

It's quite physicsy so maybe @jjgomezcadenas and/or @paolafer should take a look.

2018-07-27 19:13 UTC, jjgomezcadenas commented
@andLaing can you rebase please?
@paolafer can you review?

2018-07-28 11:35 UTC, paolafer commented
I can try, but I'm leaving for a week of holiday on August 1. If I don't manage before, I'll complete it when I'm back.

2018-07-31 08:14 UTC, paolafer requested changes
I've read the code, and I have a couple of questions, which I can ask easily to Andrew in person. Apart from that, the main thing here is that there is no test to ensure that the simulation of the low frequency noise is done correctly. I find difficult to understand if the code behaves properly, because I don't know exactly what to expect from it, and maybe a test could show that.

2018-08-10 13:21 UTC, paolafer requested changes
The code looks fine to me, and the tests added verify that the results are consistent with what is given as an input. I've just made a couple of comments to improve the readability of the code.

2018-08-10 13:21 UTC, paolafer commented on invisible_cities/sierpe/low_frequency_noise_test.py
> +    frequencies       = np.arange(15000, 20000, 500) ## subset of frequences
I think that the code would be clearer if you use a variable for the pace of `arange` (500), so that you can use the same variable below in the set of `assert`.

2018-08-10 13:21 UTC, paolafer commented on invisible_cities/sierpe/low_frequency_noise_test.py
> +    ## Which should be the same and which not depends on
This comment is totally unintelligible to me. Could you please add some punctuation, correct typos and use a name instead of "they"?

2018-08-10 14:52 UTC, paolafer approved these changes
Great! I approve this PR. Please, rebase and see if Travis is merciful with you...

2018-08-12 19:12 UTC, merged