Copy generator info in HDF5 MC files
next-exp/IC pull request #506
Opened 2018-07-24 21:23 UTC by msorel

This is to pass through MC generator info through the various IC processing steps. This is the 'generators' dataset in the 'MC' group, and contains 'evt_number', 'atomic_number', 'mass_number' and 'region' information, that changes event-by-event. 

This additional information is necessary for the background MC production, mixing many background generators in the same file.

The test 'test_copy_mc_generator_info' has been created. It  is meant to cover three cases:

    1. mcfile_withgeneratorinfo: MCRD file where 'MC' group has 'generators' dataset with non-zero dimension, equal to number of events in file. Produced with GATE version v1_03_00 or later, and from nexus file where GATE event string store contains "/Generator/IonGun/atomic_number", "/Generator/IonGun/mass_number" and "/Generator/IonGun/region" information

    2. mcfile_withemptygeneratorinfo: MCRD file where 'MC' group has 'generators' dataset with zero dimension. Produced with GATE version v1_03_00 or later, and from nexus file where GATE event string store does NOT contain "/Generator/IonGun/atomic_number", "/Generator/IonGun/mass_number" and "/Generator/IonGun/region" information

    3. mcfile_withoutgeneratorinfo: MCRD file where 'MC' group has NO 'generators' dataset. Produced with GATE version prior to v1_03_00

2018-07-24 22:37 UTC, jjgomezcadenas commented
@paolafer can you review this PR?

2018-07-25 08:37 UTC, paolafer commented
Ok, I will.

2018-07-25 10:27 UTC, paolafer requested changes
Nice workaround, Michel! It looks like it works fine.
I've just a minor comment regarding a variable in the code.

2018-07-25 10:27 UTC, paolafer commented on invisible_cities/io/mcinfo_io.py
> +    h5generators = mc_info.generators
It seems that the `h5generators` variable is not used in this method, right? If so, remove it.

2018-07-25 15:51 UTC, msorel commented
thanks @paolafer , you are right, i have removed the unused variable

2018-07-26 06:10 UTC, paolafer approved these changes

2018-07-26 06:40 UTC, merged