Removing hard-coded parameters in irene
next-exp/IC pull request #686
Opened 2019-12-17 12:00 UTC by ausonandres

The purpose of this PR is to remove some parameters (pmt_sample_frequency=25 ns, sipm_sample_frequency=1 mus, and ratio=40) that were hard-coded in some functions of `peak_functions.py`. Now, they are defined in the input of the city (since they should not change their values), and could be specified in config file.

2020-01-07 11:04 UTC, andLaing requested changes
Generally good, just a few minor points.

I'd prefer there were a way to get the correct binning from the file or database to save errors but the PMap protections should be enough for now though I suspect there might have to be further changes to accommodate the version with PMT rebin pre-selection

You need to rebase too. Maybe do it pre changes to limit clashes.

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene.py
> +from .. core.system_of_units_c import units
Line up the imports

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene_test.py
> +import pytest
I'd use the same format as for the other imports so:
instead of `import pytest`
use `from pytest import raises`

And the same for any other one that you need

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene.py
> +          pmt_sample_f=25*units.ns, sipm_sample_f=1*units.mus):
I'm not sure that I'm happy with the names. The f means frequency, I assume but the value isn't really a frequency but a width. It's not that important maybe but something like 'pmt_samp_wid' might be a bit more correct without making the name too long

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene_test.py
> +    msg += "sipms has length 3\n"
I'm not really a fan of this comparison where you're explicitly writing a copy of the error message. Unfortunately, I don't see an obvious fix for it without changing the PMap definition to have the error messages accessible.

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene_test.py
> +                 sipm_sample_f = sipm_sample_f))
Line them up

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/cities/irene_test.py
> +        assert irene(**conf)
You don't need the assert here

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/reco/peak_functions.py
> +               pmt_sample_f =25*units.ns,
Watch spacing

2020-01-07 11:04 UTC, andLaing commented on invisible_cities/reco/peak_functions.py
> +                           sipm_sample_f = sipm_sample_f,
alignment

2020-01-09 14:23 UTC, ausonandres commented
Thank you for the comments. Regarding the first one, the idea was to allow the possibility of specifying pmt and sipm sample widths in the config file, but if you don't want to, standard values will be set at the beginning of the city. The rest of suggestions have been applied.

2020-01-10 13:18 UTC, andLaing approved these changes
Some simple changes that remove hardwired numbers from the PMap construction steps. Makes things more flexible for future updates and is tested.

2020-01-10 14:30 UTC, merged