Source for nexus full simulation
next-exp/IC pull request #721
Opened 2020-05-25 18:36 UTC by andLaing

Adds a source to compoments which reads the nexus sensor response output and returns a dictionary.

Valid for NEW, NEXT100 and DEMO++

2020-08-05 07:55 UTC, jmalbos commented
The new function (`components.mcsensors_from_file`) is quite straightforward, given that it relies on existing functions to do most of the legwork. The two new tests only evaluate the failure conditions for non-valid input files. Do we need to test as well that the data yielded is correct?

2020-08-05 17:25 UTC, andLaing commented
I could add another simple test to look that the dictionary structure is what we expect. Most of this is already tested in the tests of the actual reader though. Maybe it's worthwhile adding something to make sure that we get the right number of sensors out of the splitting into pmts and sipms etc. I'll look into it.

2020-09-18 14:20 UTC, andLaing commented
could I get someone to have a look at this most recent version. It's the only ingredient missing to write the city.

2020-09-18 14:21 UTC, jmalbos commented
> could I get someone to have a look at this most recent version. It's the only ingredient missing to write the city.

I'll do it.

2020-09-21 11:14 UTC, jmalbos requested changes
This _pull request_ adds a new data source that reads the _nexus_ sensor response output and yields a dictionary as expected by `dataflow`. The code is straightforward, given that it relies on existing functions to do most of the legwork. 

Three new tests are added to IC in this PR: the first two check the behavior of the new function when the input datafile does not conform to the standard; the third test makes sure that the returned information is correct.

Once a small typo is fixed in the docstring of the function, I'll approve the PR.

2020-09-21 11:14 UTC, jmalbos commented on invisible_cities/cities/components.py
> +    file_names : List of strings
`file_names` should be `paths`

2020-09-21 13:43 UTC, jmalbos approved these changes

2020-09-21 14:48 UTC, merged