[WIP] Add city to build psfs
next-exp/IC pull request #781
Opened 2021-04-04 09:41 UTC by gonzaponte

Introduce a city to build psfs. Original code from @Aretno, I just reshaped it into a city.

Currently sitting on top of #780 (first four commits) and commit [a3eb6918](https://github.com/next-exp/IC/commit/a3eb691862f8194c0aa9b8234fa9899828cc6981), which doesn't belong here.

2021-04-06 09:42 UTC, jacg commented
Erm ... commit 237e32a, the one which adds the liquidata version ... *where* is it? I cannot find it on the `gonzaponte:psfcity` branch, be it via Magit, git CLI or the GitHub web interface.

2021-04-06 09:47 UTC, gonzaponte commented
It's in gonzaponte:flatmap. This banch hasn't been rebased yet on top of that. From what I understood [here](https://github.com/next-exp/IC/pull/780#issuecomment-813504031) this is what you wanted.

2021-04-06 09:55 UTC, jacg commented
... and it appears *here* because it references this PR. OK. And as it's an implementation of a psf city, the `psfcity` branch seemed the logical place for it to be. Hmm.

2021-04-07 15:22 UTC, Aretno requested changes
Mostly ready to go, aside from some minor fixes (many derived from the original code) I think it would be good to store the run info (or MC info in case of a MC production) in the output file. Additionally, a test checking that two files are properly combined would also be desireable.

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/config/create_psf_city.conf
> +detector_db   = 'new'
I don't see any reason to have that many empty spaces before `=`, dunno if i'm missing something.

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/cities/create_psf.py
> +        # and use df_writer directly
Agreed, as you already have the dataframe created in `combine_psfs` you might as well use the dataframe writer.

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/cities/create_psf.py
> +            selx = in_range(dst.X, xmin, xmax)
Selection should be made based on Xpeak (and Ypeak a couple lines later)

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/cities/create_psf.py
> +        # TODO: is reset_index really needed?
I think you are right and it's not needed.

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/cities/create_psf.py
> +def z_splitter(zbins, ranges, sipms):
I would change the name of this function, as it not only splits the data but also does some processing. Actually, `hdst_psf_processing` does not need to necessarily happen post z-splitting so you could have completely separate function doing the processing before doing the splitting. The caveat was that hdst_psf_processing uses groupby and memory comsumption could be delicate. Still as in a city this is executed file by flile it should be ok. I'm more inclined of having separate functions but at the very least go for another name.

2021-04-07 15:22 UTC, Aretno commented on invisible_cities/cities/create_psf.py
> +            # TODO: is this really needed?
I don't think it's needed, nope.

2021-04-08 15:14 UTC, gonzaponte commented
> I think it would be good to store the run info (or MC info in case of a MC production)

We agreed offline that since this is not done (yet) for any other city and there are no tools to do it, we leave it for another time.

> a test checking that two files are properly combined would also be desireable.

I've modified the exact-result test so it takes a case in which we split in all three coordinates and that runs over three files to make sure we check every possible feature.

I've marked all the other requests as resolved.

2021-04-09 08:51 UTC, Aretno reviewed
All good, just name the city (I'm inclined to go with Eutropia) and this is ready to go.

2021-04-09 14:19 UTC, Aretno approved these changes
This PR marks the, long overdue, formalization as a city, Eutropia, of the PSF extraction procedure. It takes penthesilea output (with a big enough rebinning so each sensor charge is fully integrated over time) to produce a set of PSFs, each one corresponding to a different region in the detector. Such regions are configurable. The PSFs are composed of their region position, the relative position sensor-event, the charge fraction seen by the sensor and the number of events used in the computation of such fraction.

Great job adapting the code @gonzaponte.

2021-04-13 10:21 UTC, gonzaponte commented
I've just added some type hints and improved alignment here and there. Please merge when we get the green flag from the GHA.

2021-04-14 10:14 UTC, merged