Fix attempt to download non-existing tables
next-exp/IC pull request #812
Opened 2022-03-09 17:50 UTC by gonzaponte

Due to the mutability of lists, this code was modifying all the elements of the dictionary. This resulted in an attempt to download tables that don't exist in the database.

2022-03-10 07:37 UTC, jacg reviewed
I believe that this does what it says on the tin. How difficult would it be to add a test?

If `tables` were a `tuple`, instead of a `list`, the original version would have worked as intended: `lhs += rhs` mutates `lhs` for mutable types (e.g. `list`) but rebinds it to a new object (`lhs + rhs`) for immutable types (e.g. `tuple`).

2022-03-10 09:30 UTC, gondiaz requested changes
Good catch, this PR does what it claims. To me is ok if you add a test, but I think changing the lists to tuples would be good enough.

Also, even though the test in `download_test.py` is skipped due to random misconnections, the `dbname` and `table` are fixed inside the function, which is parametrized. Could you fix this either removing the parametrization or the harcoded `dbname`? We may decide to activate the test in the future.

2022-03-10 10:05 UTC, gonzaponte commented
> How difficult would it be to add a test?

I'm thinking of a test that checks for the existence of the corresponding tables for each database. It's not perfect, as @gondiaz mentioned we have issues with the connection to the server. I can think of another test, but it's a bit trivial, I will push it and you can comment on that.

> Could you fix this either removing the parametrization or the harcoded dbname? 

I will take a look into that, maybe it's the same as mentioned above.

2022-03-10 10:31 UTC, jacg reviewed
Any reason why the *original* `tables` (lines 77-79) can't be a `tuple`?

2022-03-10 10:32 UTC, gonzaponte commented
No, I had just switching to that (not commited yet).

2022-03-16 16:18 UTC, gondiaz requested changes

2022-03-16 16:18 UTC, gondiaz commented on invisible_cities/database/download_test.py
> +def test_existing_tables(dbname):
Maybe `test_tables_exist` is a more descriptive name?

2022-03-16 16:18 UTC, gondiaz commented on invisible_cities/database/download_test.py
> +                                user='nextreader',passwd='readonly', db=dbname)
Cosmetics
```suggestion
    connMySql  = pymysql.connect(host="neutrinos1.ific.uv.es",
                                 user='nextreader', passwd='readonly', db=dbname)
```

2022-03-17 09:16 UTC, gondiaz approved these changes
This PR fixes a bug in downloading database tables, good work, aproved!

2022-04-26 14:51 UTC, merged