Modify detsim to read nexus files with int instead of strings
next-exp/IC pull request #870
Opened 2024-04-24 14:01 UTC by paolafer

This PR modifies a few functions all over the code, to deal with nexus files with `int` instead of `string` in some columns of their dataframes.
The main modification is in the `detsim` city, in the selection of hits in active or buffer, but a few other functions needed to be updated, too.
A test has been added to prove that the code works.

2024-04-30 17:03 UTC, gonzaponte requested changes

2024-04-30 17:03 UTC, gonzaponte commented on invisible_cities/cities/components.py
> +                           name_id      = map_df.name_id.values)
1. Why not look at the type of the label column to determine whether we need to map between ints and strings? instead of try/except?
2. I don't like the repetition. I suggest unifying both loops and inserting the ifs only for the relevant fields. e.g.
```
dict(...
     name = map_df.name.values if strings else ""
     ...)
```

2024-04-30 17:03 UTC, gonzaponte commented on invisible_cities/cities/detsim.py
> +
Again I suggest unifying both logical paths. The only difference between both is whether you select values equal to `"ACTIVE"/"BUFFER"` or `name_id[name == "ACTIVE"/"BUFFER"]`.
Also, numpy arrays contain type information in `an_array.dtype`. I would perhaps test the opposite, that is, that the array contains ints instead of strings (easier to check with `dtype`). I believe this would allow you to remove the check for zero length.

2024-04-30 17:03 UTC, gonzaponte commented on invisible_cities/io/mcinfo_io.py
> +    return pd.read_hdf(file_name, 'MC/string_map')
It's probably worth it setting the `name_id` field as the index of the dataframe, so the search you perform in `select_hits`, is a bit simpler.

2024-04-30 17:03 UTC, gonzaponte commented on invisible_cities/cities/detsim_test.py
> +
It would be great if you checked that the string map is also present in the output file.

2024-05-02 12:50 UTC, paolafer commented on invisible_cities/cities/components.py
> +                           name_id      = map_df.name_id.values)
Regarding 1., I'm having problems checking the type of the column. What don't you like about try/except?
Regarding 2, done.

2024-05-02 12:58 UTC, paolafer commented on invisible_cities/cities/detsim.py
> +
I think that the type is `int32`; how do you check that exactly? `int` does not work.

2024-05-02 13:12 UTC, paolafer commented on invisible_cities/cities/components.py
> +                           name_id      = map_df.name_id.values)
I think now it works. However, why is that better than try/except?

2024-05-02 13:20 UTC, paolafer commented on invisible_cities/cities/detsim.py
> +
I did change the code as suggested. However, I'm not sure I'm using `name_id` as an index as in another comment.

2024-05-02 13:20 UTC, paolafer commented on invisible_cities/io/mcinfo_io.py
> +    return pd.read_hdf(file_name, 'MC/string_map')
See above.

2024-05-02 13:20 UTC, paolafer commented on invisible_cities/cities/detsim_test.py
> +
Done.

2024-05-02 14:07 UTC, gonzaponte commented on invisible_cities/cities/detsim_test.py
> +    pd.read_hdf(PATH_OUT, 'MC/string_map')
Maybe check that it's not empty?

2024-05-02 14:07 UTC, gonzaponte commented on invisible_cities/cities/components.py
> +
Perhaps we can simplify this a bit more. Now you have 1 extra variable (`strings`) to keep track of whether `map_df` has a value. How about
```
map_df = load_mcstringmap(filename) if l_type == np.int32 else None
````
and later on checking if `map_df` is `None`?

2024-05-02 14:07 UTC, gonzaponte commented on invisible_cities/cities/components.py
> +                       name_id      = map_df.index.values if not strings else 0)
```suggestion
                       name         = map_df.name .values if not strings else "",
                       name_id      = map_df.index.values if not strings else 0)
```

2024-05-02 14:07 UTC, gonzaponte commented on invisible_cities/cities/components.py
> +                           name_id      = map_df.name_id.values)
try/except is too generic. You could narrow it down by looking for the specific exception thrown if the table is not found. However, in this case, there are only two possibilities: label contains strings or ints. A generic code can help misbehavior to slip through or create confusing error messages.

2024-05-02 14:11 UTC, gonzaponte commented on invisible_cities/cities/detsim.py
> +
I think I got confused with this. I thought `name_id` was a dataframe, not an array. If it were a dataframe, the best would be to do  `name_id.loc[some_label]`. Is there a good reason to split the dataframe in two arrays in `MC_hits_from_files`?

2024-05-03 08:29 UTC, gonzaponte commented on invisible_cities/cities/detsim.py
> +
Discussed offline. Will stay like this for now.

2024-05-03 09:05 UTC, gonzaponte approved these changes
A necessary update to deal with the change in the file structure produced upstream. Good job!

2024-05-13 15:42 UTC, merged